FROM golang:1.19-alpine
# Support CGO and SSL
RUN apk --no-cache add gcc g++ make
RUN apk add git
WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN GOOS=linux go build -ldflags="-s -w" -o ./bin/chat-app ./*.go
RUN apk update && apk add bash
RUN chmod +x wait-for-it.sh
EXPOSE 8080